// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Robot;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import com.revrobotics.spark.*;;
 //rename to Launcher.java
public class Climber extends SubsystemBase {

private SparkMax Motor1;
private SparkMax Motor2;



    public Climber() {
        // Create motor
        Motor1 = new CANSparkMax(11, MotorType.kBrushed);
        Motor2 = new CANSparkMax(12, MotorType.kBrushed);
 
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void runMotor (double value)
    {
        // moves the motor
        Motor1.set(value);
        Motor2.set(value);

    }
    public void stop( )
    {
        // moves the motor
        //Robot.printYellow("stopping Launcher");
        Motor1.set(0);
        Motor2.set(0);
    }
    
}