
// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
//import java.util.concurrent.TimeUnit;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.wpilibj2.command.Command;
//import frc.robot.Constants;

import frc.robot.subsystems.Launcher;

import frc.robot.subsystems.Feed;



 
public class AutonomousCommand extends Command {
    Launcher launcher;
    Feed feed;
    private int sleepCounter;
    private Pose2d position;


    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        launcher = new Launcher();
        feed = new Feed();

        sleepCounter = 0;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        sleepCounter++;
        if (sleepCounter <=1) {
            launcher.runMotor(70);
        }
        else if (sleepCounter == 60)
        {
            feed.runMotor(70);
        }
        else if (sleepCounter == 90)
        {
            launcher.stop();
            feed.stop();

            // Get current position
            //position = 

            //Start driving out to Position
        }
        else if (sleepCounter > 100)
        {
            // Stop the robot
        }
    }


    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
            return false;
    }

    @Override
    public boolean runsWhenDisabled() {

        return false;


    }
}
